name: mboacare
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.3.0
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  google_sign_in: ^6.1.4
  flutter_spinkit: ^5.2.0
  url_launcher: ^6.1.12
  url_launcher_web: ^2.0.18
 # webview_flutter: ^2.0.13
  flutter_form_builder: ^9.1.0
  image_picker: ^1.0.4
  file_picker: ^4.0.0
  provider: ^6.0.5
  cloud_firestore: ^4.8.4
  firebase_storage: ^11.2.5
  flutter_localization: ^0.1.13
  google_maps_flutter: ^2.4.0
  intl: ^0.18.0
  http: ^1.1.0
  flutter_svg: ^2.0.7
  iconsax: ^0.0.8
  google_fonts: ^6.1.0
  dio: ^4.0.0
  http_parser: ^4.0.2
  location: ^5.0.3
  uuid: ^4.1.0
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  

  connectivity_plus: ^5.0.1
  intl_phone_number_input: ^0.7.3+1

  json_annotation: ^4.8.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.0
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.3.0
  mockito: ^5.4.2
  nock: ^1.2.3
  multiselect: ^0.1.0
  get: ^4.6.6
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.6.0

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: fonts/Inter-VariableFont_slnt,wght.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
